name: CookieDough
version: '${version}'
main: com.cookiebuild.cookiedough.CookieDough
api-version: '1.20'
load: POSTWORLD
authors: [Guillaume Claverie]
description: New Cookie Build Core plugin
website: cookie-build.com
commands:
  lobby:
    description: Teleport to the lobby
    usage: /<command>
    aliases: [ hub ]
  messagetest:
    description: Test the automatic message scheduler
    usage: /<command> [send|status|info]
    permission: cookiedough.admin
